ToDoMVC/Models/ErrorViewModel.cs
namespace ToDoMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoMVC/Models/Tarefa.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace ToDoMVC.Models
{
    public class Tarefa
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [Required]
        [StringLength(200)]
        public string Description { get; set; }
    }
}

ToDoMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ToDoMVC.Models;

namespace ToDoMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDoMVC/Controllers/TarefaController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoMVC.Models;
using ToDoMVC.Repositories.Interfaces;

namespace ToDoMVC.Controllers
{
    public class TarefaController : Controller
    {
        private readonly ITarefas tarefasRepository;

        public TarefaController(ITarefas tarefasRepository)
        {
            this.tarefasRepository = tarefasRepository;
        }

        public async Task<IActionResult> Listar()
        {
            var tarefas = await tarefasRepository.GetTarefas(); 
            return View(tarefas);
        }

        [HttpPost]
        public async Task<IActionResult> Adicionar(string name, string description)
        {
            if(name != null && description != null)
            {
                var tarefa = new Tarefa { Name = name, Description = description };

                await tarefasRepository.CreateTarefa(tarefa);

                TempData["MensagemDeSucesso"] = "Tarefa adicionada com sucesso!";

                return RedirectToAction("Listar");
            }

            TempData["MensagemDeErro"] = "Por favor, preencha todos os campos.";

            return RedirectToAction("Listar");
        }

        [HttpPost]
        public async Task<IActionResult> Atualizar(string name, string description, int id)
        {
            Tarefa tarefa = new Tarefa { Name = name, Id = id, Description = description };

            if (!string.IsNullOrEmpty(name) && !string.IsNullOrEmpty(description))
            {
                if (tarefa.Id == id)
                {
                    await tarefasRepository.UpdateTarefa(tarefa, id);

                    TempData["MensagemDeSucesso"] = "Tarefa atualizada com sucesso!"; 
                }
            }
            else
            {
                TempData["MensagemDeErro"] = "Por favor, preencha todos os campos.";
            }

            return RedirectToAction("Listar");
        }

        [HttpPost]
        public async Task<IActionResult> Apagar(int id)
        {
            await tarefasRepository.DeleteTarefa(id);

            return RedirectToAction("Listar"); 
        }
    }
}

ToDoMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">CRUD de Tarefas</h1>
    <p>Esse sistema tem como objetivo realizar um CRUD de tarefas do cotidiano.</p>
</div>

ToDoMVC/Views/Shared/_Footer.cshtml
<style>
    footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        white-space: nowrap;
        line-height: 60px;
    }
</style>

<footer class="border-top footer text-muted">
        &copy; 2023 - ToDoMVC
</footer>

ToDoMVC/Views/Shared/_Header.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoMVC</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Tarefa" asp-action="Listar">Tarefas</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

ToDoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="../Views//Shared/_Footer.cshtml.css" />
</head>
<body>
    @RenderBody()

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoMVC/Views/Tarefa/Listar.cshtml
@model IEnumerable<ToDoMVC.Models.Tarefa>

@{
    ViewData["Title"] = "Listagem";
}

<style>
    #toast-warn{
        position: fixed;
        top: 10px;
        right: 10px; 
    }



</style>

<div class="container-tarefas">
    <partial name="_Header" />

    <div class="d-flex p-2 align-items-center justify-content-between">
        <h1 style="margin-bottom: 20px">Listagem de Tarefas</h1>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Adicionar
        </button>
    </div>

    <table class="table table-bordered text-center">
        <thead>
            <tr>
                <th>Id Tarefa</th>
                <th>Nome Tarefa</th>
                <th>Descrição Tarefa</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>

                    <td>
                        <div class="btn-group align-items-center justify-content-center" role="group" aria-label="Basic mixed styles example">
                            <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#modalTarefa-@item.Id" style="margin-right: 10px">Alterar</button>
                            <form method="post" asp-controller="Tarefa" asp-action="Apagar" asp-route-id="@item.Id">
                                <button type="submit" class="btn btn-danger">Apagar</button>
                            </form>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @if (TempData["MensagemDeErro"] != null)
    {
        <div id="toast-warn" class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                <strong class="me-auto">Atenção!</strong>
                <small>Agora</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body">
                @TempData["MensagemDeErro"]
            </div>
        </div>

        <script>
            setTimeout(() => {
                $('#toast-warn').toast('hide');
            }, 1500);
        </script>
    }

    @if (TempData["MensagemDeSucesso"] != null)
    {
        <div id="toast-warn" class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                <strong class="me-auto">Atenção!</strong>
                <small>Agora</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body">
                @TempData["MensagemDeSucesso"]
            </div>
        </div>

        <script>
            setTimeout(() => {
                $('#toast-warn').toast('hide');
            }, 1500);
        </script>
    }


    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Adicionar Tarefa</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form asp-controller="Tarefa" asp-action="Adicionar" method="post">
                        <div class="mb-3">
                            <label class="form-label">Nome da Tarefa</label>
                            <input type="text" class="form-control" name="name">
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Descrição</label>
                            <input type="text" class="form-control" name="description">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Fechar</button>
                            <button type="submit" class="btn btn-primary">Adicionar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @foreach (var item in Model)
    {
        <div class="modal fade" id="modalTarefa-@item.Id" tabindex="-1" aria-labelledby="modalTarefaLabel-@item.Id" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="modalTarefaLabel-@item.Id">Atualizar Tarefa</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form asp-controller="Tarefa" asp-action="Atualizar" method="post">
                        <div class="modal-body">
                            <label class="form-label">Id da Tarefa</label>
                            <input class="form-control" value="@item.Id" readonly name="id" />
                            <label class="form-label">Nome da Tarefa</label>
                            <input class="form-control" value="@item.Name" name="name" />
                            <label class="form-label">Descrição da Tarefa</label>
                            <input class="form-control" value="@item.Description" name="description" />
                        </div>


                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Fechar</button>
                            <button type="submit" class="btn btn-primary">Atualizar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    }

    <partial name="_Footer" />
</div>